/*
 * Freeze the handful of MDI paths the demo needs into demo/icons.js.
 *
 * The demo has no bundler and the card itself has no icon dependency at all — in Home
 * Assistant `<ha-icon>` is real and draws these itself. This exists so the demo page,
 * and therefore the README screenshots, look like the real thing rather than like a row
 * of emoji. Run it again only if the demo starts using a new icon:
 *
 *   npm run icons
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import * as mdi from "@mdi/js";

const ROOT = fileURLToPath(new URL("..", import.meta.url));

// mdi:drag-horizontal-variant -> mdiDragHorizontalVariant
const camel = (name) =>
  "mdi" + name.slice(4).split("-").map((p) => p[0].toUpperCase() + p.slice(1)).join("");

const ICONS = [
  // used by the card itself
  "mdi:drag-horizontal-variant", "mdi:plus", "mdi:chevron-down", "mdi:chevron-up",
  "mdi:check", "mdi:delete-outline", "mdi:text", "mdi:alert-circle-outline",
  "mdi:format-list-checks",
  // used by the demo's example configs
  "mdi:alert-octagon", "mdi:cart", "mdi:calendar-clock", "mdi:tray-full",
  "mdi:progress-wrench", "mdi:check-decagram", "mdi:silverware-fork-knife",
  "mdi:broom", "mdi:sofa", "mdi:shower", "mdi:bed", "mdi:hammer-wrench",
];

const missing = ICONS.filter((n) => !mdi[camel(n)]);
if (missing.length) {
  console.error("not in @mdi/js:", missing.join(", "));
  process.exit(1);
}

const body = ICONS.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(mdi[camel(n)])},`).join("\n");
await writeFile(
  join(ROOT, "demo", "icons.js"),
  `// Generated by scripts/gen-icons.mjs — do not edit by hand.\n` +
  `// Material Design Icons (Apache 2.0), only the paths the demo page draws.\n` +
  `export const ICON_PATHS = {\n${body}\n};\n`
);
console.log(`demo/icons.js — ${ICONS.length} paths`);
